[package]
name = "auth-test"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.22.1"
curl = {version="0.4.46", features = ["ntlm"]}
ntlmclient = "0.1.0"
reqwest = {version="0.12.7", features = ["blocking"]}
